### ISSUE TITLE
Error when adding library to project.

### ISSUE THREAD

**Issue by Martijn-Luijckx** [timherreijgers/Domotics-base#27]
when using platformIO to add this library, the compiler gives the following error when building:

`Error: Could not find the package with 'timherreijgers/DomoticsBase @ ^0.2.0-alpha' requirements for your system 'windows_amd64'`

If this is user error, please add how to in the readme.

**Comment by timherreijgers** [comment]
I looks like this is caused by the weird way I handle the versioning atm. As the library is still in early development I decided to add the "-alpha" tag. This causes platformio to behave weirdly when using the ^ prefix. I will remove the "-alpha" prefix in the next version, which would solve this issue. If this issue still persists, I will look into this again.

**Comment by timherreijgers** [comment]
Solved by the proposed solution
